//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by application.rc
//
#define IDI_APP_ICON                    101
#define IDC_CURSOR_EDITOR_SELECTION_CONTENT_CLONE 102
#define IDC_CURSOR_EDITOR_SELECTION_CONTENT_CUT 103
#define IDC_CURSOR_EDITOR_SELECTION_CONTENT_MOVE 104
#define IDC_CURSOR_EDITOR_SELECTION_RECT_CREATE 105
#define IDC_CURSOR_EDITOR_SELECTION_RECT_MOVE 106
#define IDC_CURSOR_EDITOR_HAND_CLOSED   107
#define IDC_CURSOR_EDITOR_HAND_OPEN     108
#define IDC_CURSOR_EDITOR_DRAW          109
#define IDC_CURSOR_EDITOR_FLOODFILL     110
#define IDC_CURSOR_EDITOR_ERASE         111
#define IDC_CURSOR_EDITOR_DRAWENTITY    112
#define IDC_CURSOR_EDITOR_TILEPICKER    113
#define IDC_CURSOR_EDITOR_ENTITYPICKER_INVALID 114
#define IDC_CURSOR_EDITOR_ENTITYPICKER_VALID 115
#define IDC_CURSOR_EDITOR_ADDNOTE       116
#define IDC_CURSOR_GAME                 118

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
