#ifndef INC_TT_PLATFORM_TT_ENDIANESS_H
#define INC_TT_PLATFORM_TT_ENDIANESS_H

#if defined(TT_PLATFORM_WIN)
#define TT_PLATFORM_LITTLE_ENDIAN 1
#define TT_PLATFORM_BIG_ENDIAN 0
#else
#define TT_PLATFORM_LITTLE_ENDIAN 0
#define TT_PLATFORM_BIG_ENDIAN 1
#endif

#endif // INC_TT_PLATFORM_TT_ENDIANESS_H
