CMAKE_MINIMUM_REQUIRED(VERSION 3.1)

include(FileInformation)

function(CopyAssetFiles dest_asset_dir)
    file(MAKE_DIRECTORY ${dest_asset_dir})
    foreach(_asset ${ARGN})
      string(REGEX REPLACE "^([^@]+)@?.*" "\\1" _source "${_asset}")
      if (_asset MATCHES "@")
        string(REGEX REPLACE "^([^@]+)@(.*)$" "\\2" _dest "${_asset}")
      else()
        get_filename_component(_dest "${_source}" NAME)
      endif()
      configure_file("${_source}" "${dest_asset_dir}/${_dest}" COPYONLY)
    endforeach()
endfunction()

function(CalculateDirectorySize directory out_var)
    file(GLOB_RECURSE _files ${directory}/*)
    set(total_size 0)
    foreach(_file ${_files})
        file(SIZE "${_file}" _file_size)
        math(EXPR total_size "${total_size} + ${_file_size}")
    endforeach()
    set(${out_var} ${total_size} PARENT_SCOPE)
endfunction()
